# Homebrew and user tools (portable across usernames).
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv zsh)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv zsh)"
fi
export PATH="$HOME/.local/bin:$PATH"
[[ -d /Applications/Xcode.app/Contents/Developer ]] && export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
